on:
    push:
        branches: ["main", "feature/raisa-cicd", "npm-latest-publish"]
    pull_request:
        branches: ["main", "npm-latest-publish"]

jobs:
    npmPublish:
        runs-on: ubuntu-latest
        steps:
          - name: Publish npm package when version is updated
            uses: JS-DevTools/npm-publish@v3
            with:
              token: ${{ secrets.NPM_TOKEN }}