name: Slack Notification of CI Status

on: 
    push:
        branches: ["feature/raisa-cicd"]
    pull_request:
        branches: ["feature/raisa-cicd"]
            
jobs:
    slackNotification:
        name: Slack CI status message
        runs-on: ubuntu-latest
        steps:            
            - name: Slack Notify on Failure
              if: ${{ success() }}
              id: slack
              uses: slackapi/slack-github-action@v1.24.0
              with:
                channel-id: 'C067F896WG5'
                slack-message: "Github CI result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
                # SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                # SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK