name: Slack Notification of CI Status

on: 
    push:
        branches: ["feature/raisa-cicd"]
            
jobs:
    slackNotification:
        name: Slack CI status message
        runs-on: ubuntu-latest
        steps:            
            - name: Slack Notify on Failure
              uses: slackapi/slack-github-action@v1.24.0
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK